name: Run panlint
on: [push, pull_request]

jobs:
  panlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # we need the full repo or HEAD^ does not work
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3
      - name: Install dependencies
        run: pip install colorama prettytable six
      - name: Install panlint
        run: |
          wget -q https://raw.githubusercontent.com/quattor/pan/master/panc/src/main/scripts/panlint/panlint.py -O /tmp/panlint.py
          chmod u+x /tmp/panlint.py
      - name: run panlint
        run: git diff --name-only HEAD^ | grep '\.pan$' | xargs -r /tmp/panlint.py --allow_mvn_templates || exit 1
